/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lantern_launcher_vpnservice_EchoUtils */

#ifndef _Included_com_lantern_launcher_vpnservice_EchoUtils
#define _Included_com_lantern_launcher_vpnservice_EchoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lantern_launcher_vpnservice_EchoUtils
 * Method:    stringFromJNI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lantern_launcher_vpnservice_EchoUtils_stringFromJNI
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
